import * as real from './api-modules';
import * as mock from './mock';

const useMock = import.meta.env.VITE_USE_MOCK_API === 'true';

export const {
    requestOtp,
    verifyOtp,
    setPin,
    getMerchantDashboard,
    getMerchantStats,
    getProfile,
    createProfile,
    listPlans,
    getPlan,
    previewPlan,
    createPlan,
    getConfirmationContext,
    confirmPlan,
    rejectPlan,
    cancelPlan,
    disputePlan,
    startPaymentRegistrationSession,
    recordPayment,
    confirmPayment,
    listPayments,
    listPaymentHistory,
    getPaymentStats,
    listCustomers,
    getCustomer,
    getCustomerDetail,
    getCustomerDashboard,
    listNotifications,
    markRead,
    listDisputes,
    createDispute,
    resolveDispute,
    addDisputeNote,
    resolveMerchantDispute,
    getCustomerScore,
} = useMock ? mock : real;
